from .delft import Delft
from .amsterdam import Amsterdam
from .utrecht import Utrecht
from .eindhoven import Eindhoven
from .leiden import Leiden
from .groningen import Groningen
from .erasmus import Erasmus
from .vrije import Vrije
from .twente import Twente
from .radbound import Radboud
from .maastricht import Maastricht
