from .lund import Lund
from .kth import KTH
from .uppsala import Uppsala
from .stockholm import Stockholm
from .chalmers import Chalmers
from .gothenburg import Gothenburg
from .linkoping import Linkoping
from .lulea import Lulea
from .umea import Umea
